### ISSUE TITLE
webpack的文档链接失效了

### ISSUE THREAD

**Issue by zhengziheng** [cucygh/fe-material#2]

**Comment by beupgo** [comment]
https://webpack.docschina.org/可以打开的，试试看

**Comment by zhengziheng** [comment]
谢谢回复，现在能打开了，估计是之前服务器抽风了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 舒克・贝塔 <notifications@github.com>
发送时间: Wednesday, July 18, 2018 2:28:17 PM
收件人: cucygh/fe-material
抄送: zhengziheng; Author
主题: Re: [cucygh/fe-material] webpack的文档链接失效了 (#2)


https://webpack.docschina.org/可以打开的，试试看<https://webpack.docschina.org/%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E7%9A%84%EF%BC%8C%E8%AF%95%E8%AF%95%E7%9C%8B>

―
